---
- hosts: all
  pre_tasks:
    - name: "installing testing packages"
      action: package
              name=which,wget
              state=installed
      when: ansible_os_family != 'Debian'
    - name: "installing testing packages"
      action: package
              name=wget
              state=installed
      when: ansible_os_family == 'Debian'
  roles:
    - role: unifi-controller
