---
- name: install dependencies
  apt:
    name: "{{ unifi_package_dependencies }}"
    state: present
  become: yes

- name: install ubnt apt key
  apt_key:
    keyserver: "{{ unifi_repo_key_server }}"
    id: "{{ unifi_repo_key_id }}"
  become: yes

- name: install ubnt apt repository
  apt_repository:
    filename: "{{ unifi_repo_name }}"
    repo: "{{ unifi_repo_url }}"
    state: "{{ unifi_repo_state }}"
  become: yes
  when: ansible_os_family == "Debian"

- name: install java packages
  apt:
    allow_unauthenticated: yes
    name: "{{ unifi_java_packages }}"
    state: "{{ unifi_packages_state }}"
    update_cache: yes
  become: yes
  notify:
    - restart unifi

- name: install unifi-controller packages
  apt:
    allow_unauthenticated: yes
    name: "{{ unifi_packages }}"
    state: "{{ unifi_packages_state }}"
    update_cache: yes
  become: yes
  notify:
    - restart unifi

- name: update snappy java
  get_url:
    url: "{{ unifi_java_snappy_url }}"
    checksum: "{{ unifi_java_snappy_checksum }}"
    dest: "{{ unifi_java_snappy_file }}"
  become: yes
  notify:
    - restart unifi

- name: disable mongodb default instance
  lineinfile:
    path: '{{ unifi_mongodb_config }}'
    regexp: '^ENABLE_MONGODB='
    line: 'ENABLE_MONGODB=no'
  become: yes
  notify:
    - restart mongodb

- name: configure java for unifi
  lineinfile:
    create: yes
    path: '{{ unifi_config_file }}'
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ unifi_java_home }}'
  become: yes
  notify:
    - restart unifi

- name: manage services
  service:
    name: "{{ item }}"
    state: "{{ unifi_services_state }}"
    enabled: "{{ unifi_services_enabled }}"
  become: yes
  with_items: "{{ unifi_services }}"
